locators:
  operators:
    window: main
    type: coordinate
    relative_to: window
    x: 317
    y: 38
    move_duration: 0.15
    hover_delay: 0.15
    after_delay: 1.5

  operators.acc:
    window: main
    type: coordinate
    relative_to: screen
    x: 317
    y: 965
    before_delay: 0.8
    move_duration: 0.2
    hover_delay: 0.3
    after_delay: 1.0

  operators.bb:
    window: main
    type: coordinate
    relative_to: screen
    x: 317
    y: 989
    before_delay: 0.8
    move_duration: 0.2
    hover_delay: 0.3
    after_delay: 1.0

  operators.acc.set_irradiance:
    window: main
    type: coordinate
    relative_to: screen
    x: 562
    y: 1031
    before_delay: 0.8
    move_duration: 0.2
    hover_delay: 0.3
    after_delay: 1.0
    opens_window: input_value

  operators.acc.get_irradiance:
    window: main
    type: coordinate
    relative_to: screen
    x: 562
    y: 1055
    before_delay: 0.8
    move_duration: 0.2
    hover_delay: 0.3
    after_delay: 1.0
